name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build image
      run: docker build -t sathwik345678/mongo-app-demo:${{ github.run_number }} .
    - name: Push image
      run: docker push sathwik345678/mongo-app-demo:${{ github.run_number }}
