name: workflow dispatch implement

on:
  workflow_dispatch:
    inputs:
      VALUE:
        default: string_input
        required: true
        description: The value we are going to echo

jobs:
  loud:
    runs-on: ubuntu-latest
    env:
      value: ${{ github.event.inputs.VALUE }}
    steps:
      - name: Display message
        run: echo "This is the value that was passed:$value"
